phpmyadmin:
  image: 'phpmyadmin/phpmyadmin:latest'
  restart: on-failure
  environment:
{{- if (.Values.mysql_host)}}
    PMA_HOST: ${mysql_host}
{{- end}}
{{- if eq .Values.mysql_arbitrary "yes"}}
    PMA_ARBITRARY: 1
{{- end}}
    tty: true
    stdin_open: true

