phpmyadmin:
  labels:
      io.rancher.stack.name: $${stack_name}
      {{- if ne .Values.SERVER_HOST_LABEL ""}}
      io.rancher.scheduler.affinity:host_label: ${SERVER_HOST_LABEL}
      {{- end}}
      io.rancher.scheduler.affinity:container_label_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
  ports:
  - "${public_port}:80"
{{- if (.Values.mysql_source)}}
  external_links:
    - ${mysql_source}:mysql
{{- end}}
  image: 'phpmyadmin/phpmyadmin:latest'
  restart: on-failure
  environment:
{{- if (.Values.mysql_host)}}
    PMA_HOST: ${mysql_host}
{{- end}}
{{- if eq .Values.mysql_arbitrary "yes"}}
    PMA_ARBITRARY: 1
{{- end}}
    tty: true
    stdin_open: true
