.catalog:
  name: "phpMyAdmin"
  version: "v1"
  description: "phpMyAdmin is a free software tool written in PHP, intended to handle the administration of MySQL over the Web."
  uuid: phpmyadmin-0
  questions:
    - variable: "mysql_source"
      description: "Link to mysql service or mysql server"
      label: "MySQL source"
      type: "service"
      required: false
      default: "mysql/mysql-lb"
    - variable: "public_port"
      label: "Public Port"
      description: "Unique public port for phpMyAdmin"
      type: "int"
      default: 80
      required: true
    - variable: mysql_host
      description: "Optional, allows you to specify the mysql server to be created on image startup."
      label: "MySQL Server"
      required: false
      type: "string"
      default: "mysql"
    - variable: mysql_arbitrary
      description: "Set to 'yes' to allow use arbitrary servers."
      label: MySQL arbitrary servers
      type: "enum"
      options:
        - "yes"
        - "no"
      default: "no"
      required: false
    - variable: SERVER_HOST_LABEL
      label: "Host label for node"
      description: "Example: phpmyadmin.server=1"
      type: string
      required: false
phpmyadmin:
  scale: 1
  start_on_create: true
  health_check:
    port: 80
    interval: 3000
    unhealthy_threshold: 2
    healthy_threshold: 2
    response_timeout: 2000
    request_line: 'GET "/" "HTTP/1.0"'
