name: phpMyAdmin
description: |
  phpMyAdmin is a free software tool written in PHP, intended to handle the administration of MySQL over the Web.
version: v1
category: Applications
maintainer: TDN <ngoctd@ai-t.vn>

