scrapyd:
  ports:
  - "${public_port}:6800"
{{- if (.Values.mysql_source)}}
  external_links:
    - ${mysql_source}:mysql
{{- end}}
{{- if (.Values.redis_source)}}
    - ${redis_source}:redis
{{- end}}
{{- if (.Values.kafka_source)}}
    - ${kafka_source}:kafka
{{- end}}
{{- if (.Values.elastic_source)}}
    - ${elastic_source}:elasticsearch
{{- end}}
  image: 'cedu/scrapyd:latest'
  restart: on-failure
  environment:
{{- if (.Values.mysql_source)}}
    MYSQL_HOST: ${mysql_source}
{{- end}}
{{- if (.Values.redis_source)}}
    REDIS_HOST: ${redis_source}
{{- end}}
{{- if (.Values.kafka_source)}}
    KAFKA_HOST: ${kafka_source}
{{- end}}
{{- if (.Values.elastic_source)}}
    ELASTIC_HOST: ${elastic_source}
{{- end}}
    tty: true
    stdin_open: true
    working_dir: /var/lib/scrapyd
